# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_paradosiakoioikismoi.ui'
#
# Created: Mon Apr 14 18:54:40 2014
#      by: PyQt4 UI code generator 4.10.4-snapshot-f62fabcefe39
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(892, 695)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tableViewNomothesia = QtGui.QTableView(self.tab)
        self.tableViewNomothesia.setObjectName(_fromUtf8("tableViewNomothesia"))
        self.verticalLayout_8.addWidget(self.tableViewNomothesia)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_dapp = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_dapp.setObjectName(_fromUtf8("lineEdit_dapp"))
        self.gridLayout.addWidget(self.lineEdit_dapp, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_de = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_de.setObjectName(_fromUtf8("lineEdit_de"))
        self.gridLayout.addWidget(self.lineEdit_de, 5, 1, 1, 1)
        self.lineEdit_dgp = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_dgp.setObjectName(_fromUtf8("lineEdit_dgp"))
        self.gridLayout.addWidget(self.lineEdit_dgp, 4, 1, 1, 1)
        self.lineEdit_Pop = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_Pop.setObjectName(_fromUtf8("lineEdit_Pop"))
        self.gridLayout.addWidget(self.lineEdit_Pop, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_mw = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_mw.setObjectName(_fromUtf8("lineEdit_mw"))
        self.gridLayout.addWidget(self.lineEdit_mw, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_ilikiomenoi1 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_ilikiomenoi1.setObjectName(_fromUtf8("lineEdit_ilikiomenoi1"))
        self.gridLayout.addWidget(self.lineEdit_ilikiomenoi1, 6, 1, 1, 1)
        self.lineEdit_ilikiomenoi2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_ilikiomenoi2.setObjectName(_fromUtf8("lineEdit_ilikiomenoi2"))
        self.gridLayout.addWidget(self.lineEdit_ilikiomenoi2, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setStatusTip(_fromUtf8(""))
        self.statusbar.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.dockWidget.setFont(font)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.listViewNomoi = QtGui.QListView(self.groupBox)
        self.listViewNomoi.setToolTip(_fromUtf8(""))
        self.listViewNomoi.setObjectName(_fromUtf8("listViewNomoi"))
        self.verticalLayout.addWidget(self.listViewNomoi)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.listViewDhmoi = QtGui.QListView(self.groupBox_2)
        self.listViewDhmoi.setObjectName(_fromUtf8("listViewDhmoi"))
        self.verticalLayout_5.addWidget(self.listViewDhmoi)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBoxParadosiakoi = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxParadosiakoi.setChecked(True)
        self.checkBoxParadosiakoi.setObjectName(_fromUtf8("checkBoxParadosiakoi"))
        self.verticalLayout_3.addWidget(self.checkBoxParadosiakoi)
        self.listViewOikismoi = QtGui.QListView(self.groupBox_3)
        self.listViewOikismoi.setObjectName(_fromUtf8("listViewOikismoi"))
        self.verticalLayout_3.addWidget(self.listViewOikismoi)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionZoomOikismos = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/paradosiakoioikismoi/icons/1394568050_Zoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOikismos.setIcon(icon)
        self.actionZoomOikismos.setObjectName(_fromUtf8("actionZoomOikismos"))
        self.actionFek = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/paradosiakoioikismoi/icons/product-sales-report-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFek.setIcon(icon1)
        self.actionFek.setObjectName(_fromUtf8("actionFek"))
        self.actionAddOikismoi = QtGui.QAction(MainWindow)
        self.actionAddOikismoi.setObjectName(_fromUtf8("actionAddOikismoi"))
        self.actionAddOria = QtGui.QAction(MainWindow)
        self.actionAddOria.setObjectName(_fromUtf8("actionAddOria"))
        self.actionZoomOrio = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/paradosiakoioikismoi/icons/1394568050_Zoom_oria.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOrio.setIcon(icon2)
        self.actionZoomOrio.setObjectName(_fromUtf8("actionZoomOrio"))
        self.actionKtima = QtGui.QAction(MainWindow)
        self.actionKtima.setObjectName(_fromUtf8("actionKtima"))
        self.actionReport = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/paradosiakoioikismoi/icons/1394568131_pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon3)
        self.actionReport.setObjectName(_fromUtf8("actionReport"))
        self.menu.addAction(self.actionAddOikismoi)
        self.menu.addAction(self.actionAddOria)
        self.menu.addAction(self.actionKtima)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionZoomOikismos)
        self.toolBar.addAction(self.actionFek)
        self.toolBar.addAction(self.actionZoomOrio)
        self.toolBar.addAction(self.actionReport)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Παραδοσιακοί οικισμοί - Φόρμα αναζήτησης", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Πολεοδομική νομοθεσία", None))
        self.label.setText(_translate("MainWindow", "Πληθυσμός", None))
        self.label_2.setText(_translate("MainWindow", "Αναλογία Ανδρών – Γυναικών", None))
        self.label_6.setText(_translate("MainWindow", "Αναλογία ηλικιωμένων (65+) προς δυνητικά ενεργό πληθυσμό (15-64)", None))
        self.label_3.setText(_translate("MainWindow", "Δείκτης γήρανσης πληθυσμού", None))
        self.label_4.setText(_translate("MainWindow", "Δείκτης αντικατάστασης παραγωγικού πληθυσμού", None))
        self.label_7.setText(_translate("MainWindow", "Αναλογία (%) των ατόµων άνω των 65 ετών επί του συνολικού πληθυσµού", None))
        self.label_5.setText(_translate("MainWindow", "Δείκτης εξάρτησης", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Δημογραφικοί δείκτες 2001", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Πληθυσμιακή πυραμίδα 2001", None))
        self.menu.setTitle(_translate("MainWindow", "Θεματικά επίπεδα", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.groupBox.setTitle(_translate("MainWindow", "Νομοί", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Δήμοι", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Οικισμοί", None))
        self.checkBoxParadosiakoi.setText(_translate("MainWindow", "Προβολή μόνο παραδοσιακών οικισμών", None))
        self.actionZoomOikismos.setText(_translate("MainWindow", "Επιλογή και εστίαση στον οικισμό", None))
        self.actionFek.setText(_translate("MainWindow", "Προβολή υλικού τεκμηρίωσης", None))
        self.actionFek.setToolTip(_translate("MainWindow", "Προβολή υλικού τεκμηρίωσης", None))
        self.actionAddOikismoi.setText(_translate("MainWindow", "Οικισμοί", None))
        self.actionAddOikismoi.setToolTip(_translate("MainWindow", "Προσθήκη θεματικού επιπέδου", None))
        self.actionAddOria.setText(_translate("MainWindow", "Όρια παραδοσιακών οικισμών", None))
        self.actionZoomOrio.setText(_translate("MainWindow", "Επιλογή και εστίαση στο όριο", None))
        self.actionZoomOrio.setToolTip(_translate("MainWindow", "Επιλογή και εστίαση στο όριο", None))
        self.actionKtima.setText(_translate("MainWindow", "Ορθοφωτοχάρτες (Εθνικό Κτηματολόγιο)", None))
        self.actionReport.setText(_translate("MainWindow", "Δημιουργία αναφοράς σε μορφή pdf", None))

import resources_rc
